name: Deploy Angular UI to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - "src/**"
      - "angular.json"
      - "package*.json"
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      # ⬅️ Replace <repo> with your EXACT repo name (case-sensitive)
      - name: Build Angular
        run: npm run build -- --configuration=production --base-href="/<repo>/"

      # Debug: show where Angular put index.html
      - name: List dist
        run: |
          echo "---- dist tree ----"
          ls -la dist || true
          echo "---- dist/demo ----"
          ls -la dist/demo || true
          echo "---- dist/demo/browser ----"
          ls -la dist/demo/browser || true

      # Pick the correct output folder
      - name: Determine artifact path
        id: where
        run: |
          if [ -f dist/demo/index.html ]; then
            echo "path=dist/demo" >> $GITHUB_OUTPUT
          elif [ -f dist/demo/browser/index.html ]; then
            echo "path=dist/demo/browser" >> $GITHUB_OUTPUT
          else
            echo "No index.html found in dist/demo or dist/demo/browser"; exit 1
          fi

      # SPA fallback so /routes don’t 404
      - name: Add SPA 404 fallback
        run: cp "${{ steps.where.outputs.path }}/index.html" "${{ steps.where.outputs.path }}/404.html"

      - uses: actions/configure-pages@v5

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.where.outputs.path }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
